name: Build on PR
on:
  pull_request:
    types: ["opened"]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: v18.19.0
      - name: Checkout code
        uses: actions/checkout@v2.3.1
      - name: Build the app
        shell: bash
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build:windows
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: v18.19.0
      - name: Checkout code
        uses: actions/checkout@v2.3.1
      - name: Build the app
        shell: bash
        run: |
          sudo apt install flatpak -y
          npm install -g pnpm
          pnpm install
          pnpm build:linux
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: v18.19.0
      - name: Checkout code
        uses: actions/checkout@v2.3.1
      - name: Build the app
        shell: bash
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build:mac
